//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nToggleWebTestApp {
    
    
    public partial class DynamicOff {
        
        /// <summary>
        /// WebFeatureToggle1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nToggle.WebFeatureToggle WebFeatureToggle1;
        
        /// <summary>
        /// WebFeatureToggle2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::nToggle.WebFeatureToggle WebFeatureToggle2;
    }
}
